baseURL = 'https://pair.guide/'
languageCode = 'en-us'
title = 'pair.guide - Notes on pair-coding with AI'
theme = 'pair.guide'

[permalinks]
posts = "/posts/:slug/"

[markup]
  [markup.highlight]
    noClasses = true
    style = 'monokai'